version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # AI Services
  langgraph-service:
    build: ./ai-services/langgraph
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/chatbot_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./ai-services/langgraph:/app

  # TTS Service
  tts-service:
    build: ./ai-services/tts-service
    ports:
      - "8001:8001"
    volumes:
      - ./ai-services/tts-service:/app

  # STT Service
  stt-service:
    build: ./ai-services/stt-service
    ports:
      - "8002:8002"
    volumes:
      - ./ai-services/stt-service:/app

  # API Server
  api-server:
    build: ./server/api
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/chatbot_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server/api:/app

volumes:
  postgres_data:
  redis_data:
